name: ANNIv2
version: '${project.version}'

main: net.nekozouneko.anniv2.ANNIPlugin
api-version: 1.16

authors: [Taitaitatata]
description: '${project.description}'
website: '${project.url}'

depend: [Vault, WorldEdit, WorldGuard]

commands:
  anni-admin:
    aliases: ["anniadmin"]
    description: "ANNI administration command"
    permission: anniv2.command.admin
    usage: "/<command> (arena|createMap|debug|map|set-lobby) <args>"
  anni:
    description: "ANNI command"
    permission: anniv2.command.anni
    usage: "/<command> (help|version)"
  vote:
    description: "Vote command"
    permission: anniv2.command.vote
    usage: "/<command> <map>"
  kit:
    description: "Kit command"
    permission: anniv2.command.kit
    usage: "/<command>"